/** @type {import('next-sitemap').IConfig} */
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://choosephone.co.in";

export default {
  siteUrl,
  generateRobotsTxt: true,
  sitemapSize: 7000,
  changefreq: "weekly",
  priority: 0.7,
  exclude: ["/admin", "/api/*"],

  // Add blog sitemap to index
  additionalSitemaps: [
    `${siteUrl}/sitemap-blog.xml`,
  ],

  robotsTxtOptions: {
    policies: [
      { userAgent: "*", allow: "/", disallow: ["/admin", "/api"] },
    ],
    additionalSitemaps: [
      `${siteUrl}/sitemap.xml`,      // auto-generated by next-sitemap
      `${siteUrl}/sitemap-blog.xml`, // your custom blog sitemap
    ],
  },
};
